In [62]:
%%time

from nltk.stem import SnowballStemmer 
from nltk.tokenize import word_tokenize, sent_tokenize
from collections import Counter
import math
import nltk
import os
import sys


def preprocessor(txt):
    tokens=[stemmer.stem(token.lower()) for token in tokenizer(txt) if token.isalnum()]
    return tokens

def tfidf(tok_doc, tok_corpus):
    doc_length=len(tok_doc)
    corpus_length=len(tok_corpus)

    #tf
    term_count=Counter(tok_doc)

    #idf
    tfidf={}
    for key in tok_doc:
        doc_frequency=0
        for doc in tok_corpus:
            if key in doc:
                doc_frequency+=1
        inverse_doc_frequency=math.log(corpus_length/doc_frequency)

        tfidf[key]= (term_count[key]/doc_length) * inverse_doc_frequency

    return tfidf

def task1(tok_text, tfidf_scores):

    # extract top 10
    top_10=[(k,v) for k, v in sorted(tfidf_scores.items(), key=lambda item: item[1], reverse=True)][:10]

    #print top 10
    print(', '.join([k for k,v in top_10]))

%timeit
def task2(text,tfidf_scores):
    sentences=sent_tokenize(text)
    if len(sentences)<6:
        return text # da li treba spojit s razmakom ili samo text vratit 

    sent_scores=[]
    tok_text=preprocessor(text)

    for sent in sentences:
        tok_sent=preprocessor(sent)
        tfidfs=[tfidf_scores[tok] for tok in tok_sent]
        tfidfs=np.array(tfidfs)

        if len(tfidfs)<=10:
            sent_score=sum(tfidfs)
        else:
            sent_score= np.sum(-(np.partition(-tfidfs, 10))[:10])
        print(sent_score)


        sent_scores.append((sent,sent_score))

    sentences_result=[]
#         for sent,val in sorted(sent_scores, key=lambda item: item[1], reverse=True)[:5]:
#             sentences_result.append(sent)
    if len(sent_scores)>5:
        vals=np.array([val for sent,val in sent_scores])
        for idx in ((np.argpartition(-vals, 5))[:5]):
            sentences_result.append(sent_scores[idx])
    else:
        for sent,val in sent_scores:
            sentences_result.append(sent)
    print(sentences_result)

    sentences_sorted=[]
    for sent in sentences:
        if sent in sentences_result:
            sentences_sorted.append(sent)

    print(' '.join(sentences_sorted))


# setup 
corpus_pth='data\\corpus'
input_pth='data\\corpus\\goose\\Chinese goose.txt'

tokenizer=word_tokenize
stemmer=SnowballStemmer(language='english', ignore_stopwords=False)

corpus_string=''
for root, dirs, files in os.walk(corpus_pth, topdown=False):
   for name in files:
      corpus_string+=str(
              open(os.path.join(root, name),'r', encoding='UTF-8').read()
        )

tok_corpus=preprocessor(corpus_string)

input_text=open(input_pth,'r', encoding='UTF-8').read()
tok_text=preprocessor(input_text)
tfidf_scores=tfidf(tok_text,tok_corpus)

# task 1
task1(tok_text, tfidf_scores)

# task 2
task2(input_text, tfidf_scores)  



chines, goos, breed, gees, the, knob, swan, of, femal, wild
2.148510324599202
1.8504567133793062
1.2866018496400775
0.8421373012398391
2.0953112414358794
1.6130756409113107
1.8460688892352195
1.642651057586106
2.215718724220454
[('A female Chinese goose can lay 50–60 eggs over the course of the breeding season (February to June), although there are reports of Chinese geese laying up to 100 eggs during that time.', 2.215718724220454), ('The Chinese goose is a breed of domesticated goose descended from the wild swan goose.', 2.148510324599202), ('Chinese geese differ from the wild birds in much larger size (up to 5–10 kg in males, 4–9 kg in females), and in having an often strongly developed basal knob on the upper side of the bill.', 1.8504567133793062), ('Chinese geese are a close cousin of the African goose, a heavier breed also descended from the swan goose.', 2.0953112414358794), ("While many domestic Chinese geese have a similar body type to other breeds, the breed standards as def

In [28]:
import numpy as np

In [33]:
ad=np.array([4,7,2,8,4,99,22,3,5,2643,3])
five=np.partition(-ad, 4)

In [36]:
five

array([  -99, -2643,   -22,    -8,    -7,    -5,    -4,    -3,    -4,
          -2,    -3])

In [37]:
sum(-five[:5])

2779

In [40]:
tfidfs

NameError: name 'tfidfs' is not defined

In [56]:
tfidfs=np.array([4,7,2,8,4,99,22,3,5,54,325,623])
(np.argpartition(-tfidfs, 3))[:3]

array([10, 11,  5], dtype=int64)

In [58]:
tfidfs[11]

623

In [65]:
items=np.array([4,7,2,8,4,99,22,3,5,54,325,623])

top_10_idxs=np.argpartition(-items, 5)[:5]
print(top_10_idxs)

[10 11  5  9  6]


In [66]:
items[10]

325